-- 002_add_constraints_and_indexes.up.sql

ALTER TABLE client ADD CONSTRAINT client_contact_present CHECK (phone IS NOT NULL OR email IS NOT NULL);
ALTER TABLE employee ADD CONSTRAINT employee_specialization_chk CHECK (specialization IS NULL OR specialization IN ('Оператор','Мастер'));
ALTER TABLE equipment ADD CONSTRAINT equipment_status_chk CHECK (status IN ('Зарегистрировано','Принято в сервис','На диагностике','На ремонте','Готово к выдаче','Выдано'));
ALTER TABLE request ADD CONSTRAINT request_status_chk CHECK (status IN ('Создана','Принята','На диагностике','Ожидание','В ремонте','Готова','Закрыта','Отменена'));
ALTER TABLE request ADD CONSTRAINT request_waiting_reason_chk CHECK ((status='Ожидание' AND waiting_reason IS NOT NULL) OR (status<>'Ожидание' AND waiting_reason IS NULL));
ALTER TABLE request ADD CONSTRAINT request_waiting_reason_values_chk CHECK (waiting_reason IS NULL OR waiting_reason IN ('CLIENT_APPROVAL','PART_WAITING','ADDITIONAL_DIAGNOSTICS','OTHER'));
ALTER TABLE request ADD CONSTRAINT request_repair_requires_approval_chk CHECK (status NOT IN ('В ремонте','Готова','Закрыта') OR client_approved=true);
ALTER TABLE request ADD CONSTRAINT request_approval_at_chk CHECK ((client_approved=true)=(approval_at IS NOT NULL));
ALTER TABLE request ADD CONSTRAINT request_received_after_created_chk CHECK (received_at IS NULL OR received_at>=created_at);
ALTER TABLE request ADD CONSTRAINT request_closed_requires_issued_chk CHECK (status<>'Закрыта' OR issued_at IS NOT NULL);
ALTER TABLE request ADD CONSTRAINT request_preliminary_cost_chk CHECK (preliminary_cost IS NULL OR preliminary_cost>=0);
ALTER TABLE request ADD CONSTRAINT request_total_cost_chk CHECK (total_cost IS NULL OR total_cost>=0);
ALTER TABLE master_assignment ADD CONSTRAINT master_assignment_ended_after_assigned_chk CHECK (ended_at IS NULL OR ended_at>=assigned_at);
ALTER TABLE master_assignment ADD CONSTRAINT master_assignment_active_no_end_chk CHECK ((is_active=true AND ended_at IS NULL) OR is_active=false);
ALTER TABLE work ADD CONSTRAINT work_status_chk CHECK (status IN ('Запланирована','Согласована','Выполняется','Завершена','Отменена'));
ALTER TABLE work ADD CONSTRAINT work_cost_chk CHECK (cost>=0);
ALTER TABLE work ADD CONSTRAINT work_ended_after_started_chk CHECK (ended_at IS NULL OR started_at IS NULL OR ended_at>=started_at);
ALTER TABLE repair ADD CONSTRAINT repair_status_chk CHECK (status IN ('Запланирован','Выполняется','Приостановлен','Завершён','Отменён'));
ALTER TABLE repair ADD CONSTRAINT repair_ended_after_started_chk CHECK (ended_at IS NULL OR started_at IS NULL OR ended_at>=started_at);
ALTER TABLE repair ADD CONSTRAINT repair_result_when_completed_chk CHECK (status<>'Завершён' OR result IS NOT NULL);
ALTER TABLE part ADD CONSTRAINT part_price_chk CHECK (price>=0);
ALTER TABLE part ADD CONSTRAINT part_stock_quantity_chk CHECK (stock_quantity>=0);
ALTER TABLE part_reservation ADD CONSTRAINT part_reservation_quantity_chk CHECK (quantity>0);
ALTER TABLE part_reservation ADD CONSTRAINT part_reservation_status_chk CHECK (status IN ('Активен','Использован','Отменён'));
ALTER TABLE used_part ADD CONSTRAINT used_part_quantity_chk CHECK (quantity>0);
ALTER TABLE payment ADD CONSTRAINT payment_amount_chk CHECK (amount>=0);
ALTER TABLE payment ADD CONSTRAINT payment_status_chk CHECK (status IN ('Оплачено','Не требуется'));
ALTER TABLE payment ADD CONSTRAINT payment_zero_amount_chk CHECK ((amount=0 AND status='Не требуется') OR amount>0);
ALTER TABLE payment ADD CONSTRAINT payment_paid_at_chk CHECK ((status='Оплачено')=(paid_at IS NOT NULL));
ALTER TABLE status_history ADD CONSTRAINT status_history_new_status_chk CHECK (new_status IN ('Создана','Принята','На диагностике','Ожидание','В ремонте','Готова','Закрыта','Отменена'));
ALTER TABLE status_history ADD CONSTRAINT status_history_different_statuses_chk CHECK (old_status IS DISTINCT FROM new_status);
ALTER TABLE notification ADD CONSTRAINT notification_delivery_status_chk CHECK (delivery_status IN ('Ожидает отправки','Отправлено','Ошибка'));

CREATE UNIQUE INDEX uq_equipment_manufacturer_serial ON equipment(manufacturer,serial_number) WHERE serial_number IS NOT NULL;
CREATE UNIQUE INDEX uq_master_assignment_one_active_per_request ON master_assignment(request_id) WHERE is_active;
CREATE UNIQUE INDEX uq_part_reservation_active_per_repair ON part_reservation(repair_id,part_id) WHERE status='Активен';
CREATE UNIQUE INDEX uq_used_part_repair_part ON used_part(repair_id,part_id);
CREATE INDEX idx_equipment_client ON equipment(client_id);
CREATE INDEX idx_request_equipment ON request(equipment_id);
CREATE INDEX idx_request_operator ON request(operator_id);
CREATE INDEX idx_master_assignment_request ON master_assignment(request_id);
CREATE INDEX idx_master_assignment_employee ON master_assignment(employee_id);
CREATE INDEX idx_diagnosis_master ON diagnosis(master_id);
CREATE INDEX idx_work_request ON work(request_id);
CREATE INDEX idx_repair_work ON repair(work_id);
CREATE INDEX idx_repair_master ON repair(master_id);
CREATE INDEX idx_part_reservation_part ON part_reservation(part_id);
CREATE INDEX idx_part_reservation_repair ON part_reservation(repair_id);
CREATE INDEX idx_used_part_repair ON used_part(repair_id);
CREATE INDEX idx_used_part_part ON used_part(part_id);
CREATE INDEX idx_status_history_request ON status_history(request_id,changed_at);
CREATE INDEX idx_notification_request ON notification(request_id);
