DROP INDEX IF EXISTS idx_notification_request;
DROP INDEX IF EXISTS idx_status_history_request;
DROP INDEX IF EXISTS idx_used_part_part;
DROP INDEX IF EXISTS idx_used_part_repair;
DROP INDEX IF EXISTS idx_part_reservation_repair;
DROP INDEX IF EXISTS idx_part_reservation_part;
DROP INDEX IF EXISTS idx_repair_master;
DROP INDEX IF EXISTS idx_repair_work;
DROP INDEX IF EXISTS idx_work_request;
DROP INDEX IF EXISTS idx_diagnosis_master;
DROP INDEX IF EXISTS idx_master_assignment_employee;
DROP INDEX IF EXISTS idx_master_assignment_request;
DROP INDEX IF EXISTS idx_request_operator;
DROP INDEX IF EXISTS idx_request_equipment;
DROP INDEX IF EXISTS idx_equipment_client;
DROP INDEX IF EXISTS uq_used_part_repair_part;
DROP INDEX IF EXISTS uq_part_reservation_active_per_repair;
DROP INDEX IF EXISTS uq_master_assignment_one_active_per_request;
DROP INDEX IF EXISTS uq_equipment_manufacturer_serial;

ALTER TABLE notification DROP CONSTRAINT IF EXISTS notification_delivery_status_chk;
ALTER TABLE status_history DROP CONSTRAINT IF EXISTS status_history_different_statuses_chk;
ALTER TABLE status_history DROP CONSTRAINT IF EXISTS status_history_new_status_chk;
ALTER TABLE payment DROP CONSTRAINT IF EXISTS payment_paid_at_chk;
ALTER TABLE payment DROP CONSTRAINT IF EXISTS payment_zero_amount_chk;
ALTER TABLE payment DROP CONSTRAINT IF EXISTS payment_status_chk;
ALTER TABLE payment DROP CONSTRAINT IF EXISTS payment_amount_chk;
ALTER TABLE used_part DROP CONSTRAINT IF EXISTS used_part_quantity_chk;
ALTER TABLE part_reservation DROP CONSTRAINT IF EXISTS part_reservation_status_chk;
ALTER TABLE part_reservation DROP CONSTRAINT IF EXISTS part_reservation_quantity_chk;
ALTER TABLE part DROP CONSTRAINT IF EXISTS part_stock_quantity_chk;
ALTER TABLE part DROP CONSTRAINT IF EXISTS part_price_chk;
ALTER TABLE repair DROP CONSTRAINT IF EXISTS repair_result_when_completed_chk;
ALTER TABLE repair DROP CONSTRAINT IF EXISTS repair_ended_after_started_chk;
ALTER TABLE repair DROP CONSTRAINT IF EXISTS repair_status_chk;
ALTER TABLE work DROP CONSTRAINT IF EXISTS work_ended_after_started_chk;
ALTER TABLE work DROP CONSTRAINT IF EXISTS work_cost_chk;
ALTER TABLE work DROP CONSTRAINT IF EXISTS work_status_chk;
ALTER TABLE master_assignment DROP CONSTRAINT IF EXISTS master_assignment_active_no_end_chk;
ALTER TABLE master_assignment DROP CONSTRAINT IF EXISTS master_assignment_ended_after_assigned_chk;
ALTER TABLE request DROP CONSTRAINT IF EXISTS request_total_cost_chk;
ALTER TABLE request DROP CONSTRAINT IF EXISTS request_preliminary_cost_chk;
ALTER TABLE request DROP CONSTRAINT IF EXISTS request_closed_requires_issued_chk;
ALTER TABLE request DROP CONSTRAINT IF EXISTS request_received_after_created_chk;
ALTER TABLE request DROP CONSTRAINT IF EXISTS request_approval_at_chk;
ALTER TABLE request DROP CONSTRAINT IF EXISTS request_repair_requires_approval_chk;
ALTER TABLE request DROP CONSTRAINT IF EXISTS request_waiting_reason_values_chk;
ALTER TABLE request DROP CONSTRAINT IF EXISTS request_waiting_reason_chk;
ALTER TABLE request DROP CONSTRAINT IF EXISTS request_status_chk;
ALTER TABLE equipment DROP CONSTRAINT IF EXISTS equipment_status_chk;
ALTER TABLE employee DROP CONSTRAINT IF EXISTS employee_specialization_chk;
ALTER TABLE client DROP CONSTRAINT IF EXISTS client_contact_present;
